# _config.yml

# Site settings
title: Spin
description: Your site description
theme: jekyll-theme-minimal  

# Markdown settings
markdown: kramdown  
kramdown:
  input: GFM  
  syntax_highlighter: rouge  

# Jekyll settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Liquid tags for Julia code highlighting
highlighter: rouge

