# _config.yml

# Site settings
title: Spin
description: Your site description
theme: minima  

# Markdown settings
markdown: kramdown  
kramdown:
  input: GFM  
  syntax_highlighter: rouge  


# Liquid tags for Julia code highlighting
highlighter: rouge

