# _config.yml

# Site settings
title: Spin
description: Your site description
theme: minima  

# Markdown settings
markdown: kramdown  
 


# Liquid tags for Julia code highlighting
highlighter: rouge

