# .github/workflows/deploy.yml
name: Deploy Jekyll with GitHub Pages

on:
  # Trigger on push to main branch
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build Jekyll site
        run: |
          bundle exec jekyll build --destination ./_site
        env:
          JEKYLL_ENV: production  # Set environment to production for Jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          cname: your-custom-domain.com  # Optional: set a custom domain (remove if not needed)
